#!/bin/bash
if [ $1 = "up" ]
then
	# modifier ci-dessous pour changer la barre des favoris en mode  pentest
	gsettings set org.gnome.shell favorite-apps REPLACENEW
	gsettings set org.gnome.desktop.background picture-uri file:///usr/share/kaliproject/pentest.png
	docker run -p 9800-9900:9800-9900 -ti --name lololekali --mount type=bind,source=/share/kali,target=/share/kali -h kali lololekali tmux
elif [ $1 = "down" ]
then
	# modifier ci-dessous pour changer la barre des favoris en mode normal
	gsettings set org.gnome.shell favorite-apps REPLACEOLD
	# modifier ci-dessous pour changer le fond d'écran en mode normal
	gsettings set org.gnome.desktop.background picture-uri REPLACEDESKTOP
	docker container rm lololekali
elif [ $1 = "build" ]
then
	docker build -t lololekali /usr/share/kaliproject/
elif [ $1 = "resume" ]
then
	# modifier ci-dessous pour changer la barre des favoris en mode pentest
	gsettings set org.gnome.shell favorite-apps REPLACENEW
	gsettings set org.gnome.desktop.background picture-uri file:///usr/share/kaliproject/pentest.png
	docker start -ai lololekali
elif [ $1 = "delete" ]
then
	docker image rm lololekali
else
	echo "Bienvenue dans l'aide"
	echo "		up		Lance le container"
	echo "		down		Supprime le container"
	echo "		resume		Relance le container pour reprendre un pentest"
	echo "		build		Construit l'image kali"
	echo "		delete		Supprime l'image"
	echo "Auteur : LOLOLEKIK"
fi
