#!/bin/bash
if [ $1 = "up" ]
then
	docker run -p 9800-9900:9800-9900 -ti --name lololekali --mount type=bind,source=/share/kali,target=/share/kali -h kali lololekali tmux
elif [ $1 = "down" ]
then
	docker container rm lololekali
elif [ $1 = "build" ]
then
	docker build -t lololekali /usr/share/kaliproject/
elif [ $1 = "resume" ]
then
	docker start -ai lololekali
elif [ $1 = "delete" ]
then
	docker image rm lololekali
else
	echo "Bienvenue dans l'aide"
	echo "		up		Lance le container"
	echo "		down		Supprime le container"
	echo "		resume		Relance le container pour reprendre un pentest"
	echo "		build		Construit l'image kali"
	echo "		delete		Supprime l'image"
	echo "Auteur : LOLOLEKIK"
fi
